.analytics:
  needs: []
  variables:
    PROJECT_NAME: deltafi-analytics

"ğŸ³ Publish analytics (GitLab)":
  extends:
    - .analytics
    - .docker

"ğŸ³ Publish analytics (docker.io)":
  extends:
    - .analytics
    - .docker-multiarch
