.dirwatcher:
  needs: []
  variables:
    PROJECT_NAME: deltafi-dirwatcher

"Publish deltafi-dirwatcher to GitLab ğŸ³":
  extends:
    - .dirwatcher
    - .docker

"Publish deltafi-dirwatcher to docker.io ğŸ³":
  extends:
    - .dirwatcher
    - .docker-multiarch
