.dirwatcher:
  needs: []
  variables:
    PROJECT_NAME: deltafi-dirwatcher

"ğŸ³ Publish dirwatcher (GitLab)":
  extends:
    - .dirwatcher
    - .docker

"ğŸ³ Publish dirwatcher (docker.io)":
  extends:
    - .dirwatcher
    - .docker-multiarch
