.dirwatcher:
  needs: []
  variables:
    PROJECT_NAME: deltafi-dirwatcher

"Publish deltafi-dirwatcher to GitLab :whale:":
  extends:
    - .dirwatcher
    - .docker

"Publish deltafi-dirwatcher to docker.io :whale:":
  extends:
    - .dirwatcher
    - .docker-multiarch
