apiVersion: 1
providers:
  - name: 'fileProvider'
    orgId: 1
    folder: 'DeltaFi'
    type: file
    disableDeletion: true
    allowUiUpdates: false
    updateIntervalSeconds: 30
    options:
      foldersFromFilesStructure: false
      path: /tmp/dashboards
