.egress-sink:
  needs: []
  variables:
    PROJECT_NAME: deltafi-egress-sink

"ğŸ³ Publish egress-sink (GitLab)":
  extends:
    - .egress-sink
    - .docker

"ğŸ³ Publish egress-sink (docker.io)":
  extends:
    - .egress-sink
    - .docker-multiarch
