.egress-sink:
  needs: []
  variables:
    PROJECT_NAME: deltafi-egress-sink

"Publish deltafi-egress-sink to GitLab ğŸ³":
  extends:
    - .egress-sink
    - .docker

"Publish deltafi-egress-sink to docker.io ğŸ³":
  extends:
    - .egress-sink
    - .docker-multiarch
