.clustermonitor:
  needs: []
  variables:
    PROJECT_NAME: deltafi-clustermonitor

"Publish deltafi-clustermonitor to GitLab ğŸ³":
  extends:
    - .clustermonitor
    - .docker

"Publish deltafi-clustermonitor to docker.io ğŸ³":
  extends:
    - .clustermonitor
    - .docker-multiarch
