.clustermonitor:
  needs: []
  variables:
    PROJECT_NAME: deltafi-clustermonitor

"ğŸ³ Publish clustermonitor (GitLab)":
  extends:
    - .clustermonitor
    - .docker

"ğŸ³ Publish clustermonitor (docker.io)":
  extends:
    - .clustermonitor
    - .docker-multiarch
