.clustermonitor:
  needs: []
  variables:
    PROJECT_NAME: deltafi-clustermonitor

"Publish deltafi-clustermonitor to GitLab :whale:":
  extends:
    - .clustermonitor
    - .docker

"Publish deltafi-clustermonitor to docker.io :whale:":
  extends:
    - .clustermonitor
    - .docker-multiarch
