---
apiVersion: v1
kind: Service
metadata:
  name: deltafi-victoriametrics
  namespace: deltafi
  labels:
    app: victoriametrics
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8428
    targetPort: 8428
    protocol: TCP
  - name: graphite
    port: 2003
    targetPort: 2003
    protocol: TCP
  selector:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/instance: deltafi
