{{- if .Values.deltafi.analytics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: deltafi-analytics
spec:
  selector:
    app: deltafi-analytics
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
{{- end -}}
